version: '3'

services: 
  realworld:
    build:
      context: . 
      dockerfile: ./Dockerfile
    networks:
      - realworld
    ports:
      - 8080:8080
    environment:
      SHELL: /bin/bash
      # CONFIG: 
      FLASK_APP: realworld.app
      FLASK_ENV: ${FLASK_ENV:-development}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT:-8080}
      POSTGRES_DB: ${POSTGRES_DB:-realworld}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      # temporary
      FLASK_DEBUG: 1
    depends_on:
      - postgres
    # stdin_open: true
    # tty: true

  postgres:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-realworld}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    ports:
      - 5432:5432
    networks:
      - realworld

networks:
  realworld:
    name: "realworld"
